import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from core.config import config

def plot_fcca_matrices():
    # Load the W matrices generated by evaluate_fcca.py
    w_pre = np.load(config.paths.OUTPUTS_DIR / "fcca_W_pre-ern.npy")
    w_ern = np.load(config.paths.OUTPUTS_DIR / "fcca_W_ern.npy")
    w_post = np.load(config.paths.OUTPUTS_DIR / "fcca_W_post-ern.npy")

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    
    # Plotting parameters
    vmax = max(np.max(w_pre), np.max(w_ern), np.max(w_post))
    vmin = min(np.min(w_pre), np.min(w_ern), np.min(w_post))

    titles = ['(a) Pre-ERN', '(b) ERN', '(c) Post-ERN']
    matrices = [w_pre, w_ern, w_post]

    for ax, mat, title in zip(axes, matrices, titles):
        im = ax.imshow(mat, cmap='jet', vmin=vmin, vmax=vmax, origin='lower')
        ax.set_title(title, fontsize=16, pad=10)
        ax.set_xlabel('Nodes', fontsize=12)
        ax.set_ylabel('Nodes', fontsize=12)
        # Remove ticks for cleaner look like paper
        ax.set_xticks([])
        ax.set_yticks([])

    # Add a colorbar
    cbar = fig.colorbar(im, ax=axes.ravel().tolist(), shrink=0.8)
    cbar.set_label('Consensus Probability (W)', rotation=270, labelpad=15, fontsize=12)

    plt.suptitle("Network Structures (W Matrices) for ERN Intervals (FCCA)", fontsize=18, y=1.05)
    
    # Save the plot
    save_path = config.paths.OUTPUTS_DIR / "fcca_comparison.png"
    plt.savefig(save_path, bbox_inches='tight', dpi=150)
    print(f"Plot saved successfully to {save_path}")

if __name__ == "__main__":
    plot_fcca_matrices()
